// Copyright (c) 2026 the libtailscale Dart package authors.
// SPDX-License-Identifier: BSD-3-Clause
//
// GENERATED FILE. Do not edit by hand.
// Regenerate with: cd tool/ffigen && dart run bin/generate.dart
//
// Bindings to the `tailscale_*` C API of https://github.com/tailscale/libtailscale
// (tailscale.h). Semantics: 0 = success, -1 = see tailscale_errmsg, positive
// values are errno codes (EBADF: bad handle, ERANGE: buffer too small).

// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:libtailscale/src/ffi/tailscale_bindings.g.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int Function(tailscale_listener, ffi.Pointer<tailscale_conn>)>()
external int tailscale_accept(
  int listener,
  ffi.Pointer<tailscale_conn> conn_out,
);

@ffi.Native<ffi.Int Function(tailscale)>()
external int tailscale_close(int sd);

@ffi.Native<
  ffi.Int Function(
    tailscale,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<tailscale_conn>,
  )
>()
external int tailscale_dial(
  int sd,
  ffi.Pointer<ffi.Char> network,
  ffi.Pointer<ffi.Char> addr,
  ffi.Pointer<tailscale_conn> conn_out,
);

@ffi.Native<ffi.Int Function(tailscale, ffi.Int)>()
external int tailscale_enable_funnel_to_localhost_plaintext_http1(
  int sd,
  int localhostPort,
);

@ffi.Native<ffi.Int Function(tailscale, ffi.Pointer<ffi.Char>, ffi.Size)>(
  isLeaf: true,
)
external int tailscale_errmsg(int sd, ffi.Pointer<ffi.Char> buf, int buflen);

@ffi.Native<ffi.Int Function(tailscale, ffi.Pointer<ffi.Char>, ffi.Size)>(
  isLeaf: true,
)
external int tailscale_getips(int sd, ffi.Pointer<ffi.Char> buf, int buflen);

@ffi.Native<
  ffi.Int Function(
    tailscale_listener,
    tailscale_conn,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>(isLeaf: true)
external int tailscale_getremoteaddr(
  int l,
  int conn,
  ffi.Pointer<ffi.Char> buf,
  int buflen,
);

@ffi.Native<
  ffi.Int Function(
    tailscale,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<tailscale_listener>,
  )
>()
external int tailscale_listen(
  int sd,
  ffi.Pointer<ffi.Char> network,
  ffi.Pointer<ffi.Char> addr,
  ffi.Pointer<tailscale_listener> listener_out,
);

@ffi.Native<
  ffi.Int Function(
    tailscale,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external int tailscale_loopback(
  int sd,
  ffi.Pointer<ffi.Char> addr_out,
  int addrlen,
  ffi.Pointer<ffi.Char> proxy_cred_out,
  ffi.Pointer<ffi.Char> local_api_cred_out,
);

@ffi.Native<tailscale Function()>(isLeaf: true)
external int tailscale_new();

@ffi.Native<ffi.Int Function(tailscale, ffi.Pointer<ffi.Char>)>(isLeaf: true)
external int tailscale_set_authkey(int sd, ffi.Pointer<ffi.Char> authkey);

@ffi.Native<ffi.Int Function(tailscale, ffi.Pointer<ffi.Char>)>(isLeaf: true)
external int tailscale_set_control_url(
  int sd,
  ffi.Pointer<ffi.Char> control_url,
);

@ffi.Native<ffi.Int Function(tailscale, ffi.Pointer<ffi.Char>)>(isLeaf: true)
external int tailscale_set_dir(int sd, ffi.Pointer<ffi.Char> dir);

@ffi.Native<ffi.Int Function(tailscale, ffi.Int)>(isLeaf: true)
external int tailscale_set_ephemeral(int sd, int ephemeral);

@ffi.Native<ffi.Int Function(tailscale, ffi.Pointer<ffi.Char>)>(isLeaf: true)
external int tailscale_set_hostname(int sd, ffi.Pointer<ffi.Char> hostname);

@ffi.Native<ffi.Int Function(tailscale, ffi.Int)>(isLeaf: true)
external int tailscale_set_logfd(int sd, int fd);

@ffi.Native<ffi.Int Function(tailscale)>()
external int tailscale_start(int sd);

@ffi.Native<ffi.Int Function(tailscale, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int tailscale_status_json(
  int sd,
  ffi.Pointer<ffi.Pointer<ffi.Char>> json_out,
);

@ffi.Native<ffi.Int Function(tailscale)>()
external int tailscale_up(int sd);

typedef tailscale = ffi.Int;
typedef Darttailscale = int;
typedef tailscale_conn = ffi.Int;
typedef Darttailscale_conn = int;
typedef tailscale_listener = ffi.Int;
typedef Darttailscale_listener = int;
