// Copyright (c) 2026 the libtailscale Dart package authors.
// SPDX-License-Identifier: BSD-3-Clause

import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:libtailscale/libtailscale.dart';

/// Who produced a [ChatMessage].
enum ChatDirection {
  /// Received on the listener.
  incoming,

  /// Sent by this node.
  outgoing,

  /// Generated by the app (listener started, errors, ...).
  system,
}

/// One line in the chat log.
final class ChatMessage {
  /// Creates a message.
  const ChatMessage({
    required this.at,
    required this.direction,
    required this.peer,
    required this.text,
    this.delivered = false,
  });

  /// When it was recorded.
  final DateTime at;

  /// Where it came from.
  final ChatDirection direction;

  /// Peer name or address (empty for system messages).
  final String peer;

  /// The line, without its newline.
  final String text;

  /// Outgoing only: the peer echoed the line back.
  final bool delivered;

  /// The same message marked as delivered.
  ChatMessage asDelivered() => ChatMessage(
    at: at,
    direction: direction,
    peer: peer,
    text: text,
    delivered: true,
  );
}

/// Line-oriented chat over TCP on the tailnet.
///
/// The listener echoes every line back and records it with the sender
/// resolved through `whoIs`; [send] connects to a peer's listener, writes one
/// line and waits for the echo. The wire format is one UTF-8 line per
/// message, so `tsnode echo` and `tsnode send` from `examples/tsnode/` are valid
/// counterparts. Everything network-related is a call into the library.
final class ChatService extends ChangeNotifier {
  /// Creates a service listening on [port] once attached to a node.
  ChatService({
    this.port = 7777,
    this.replyTimeout = const Duration(seconds: 5),
  });

  /// TCP port of the listener; peers send to the same port.
  final int port;

  /// How long [send] waits for the echo.
  final Duration replyTimeout;

  TailscaleNode? _node;
  TailscaleServerSocket? _server;
  StreamSubscription<TailscaleSocket>? _accepting;
  final _messages = <ChatMessage>[];
  String? _listenError;

  /// Messages, oldest first.
  List<ChatMessage> get messages => List.unmodifiable(_messages);

  /// Whether the listener is accepting connections.
  bool get listening {
    final server = _server;
    return server != null && !server.isClosed;
  }

  /// Why the listener is not running, if it failed.
  String? get listenError => _listenError;

  /// Whether a node is attached.
  bool get attached => _node != null;

  /// Uses [node] for listening and sending, and starts the listener.
  Future<void> attach(TailscaleNode node) async {
    _node = node;
    await ensureListening();
  }

  /// Starts the listener if it is not running (also used after the app
  /// resumes from the background, when a stale listener may have closed).
  Future<void> ensureListening() async {
    final node = _node;
    if (node == null || listening) return;
    try {
      final server = await node.listen(port: port);
      _server = server;
      _listenError = null;
      _accepting = server.listen(
        _serve,
        onError: (Object e) {
          _listenError = 'accept failed: $e';
          notifyListeners();
        },
        onDone: () {
          if (identical(_server, server)) {
            _server = null;
            _accepting = null;
          }
          notifyListeners();
        },
      );
      _system('listening on port $port');
    } on TailscaleException catch (e) {
      _listenError = e.message;
    } on Exception catch (e) {
      _listenError = '$e';
    }
    notifyListeners();
  }

  /// Stops the listener and forgets the node. Messages are kept.
  Future<void> detach() async {
    await _accepting?.cancel();
    _accepting = null;
    await _server?.close();
    _server = null;
    _node = null;
    _listenError = null;
    notifyListeners();
  }

  /// Empties the log.
  void clear() {
    _messages.clear();
    notifyListeners();
  }

  /// Sends [text] as one line to [host]'s listener and waits for the echo.
  ///
  /// Records the outgoing message first; marks it delivered when the same
  /// line comes back, and records a differing reply as an incoming message.
  /// Connection failures are recorded and rethrown so the UI can show them.
  Future<void> send(String host, String text) async {
    final node = _node;
    if (node == null) throw StateError('not connected');
    final line = text.trimRight();
    if (line.isEmpty) return;
    final index = _add(
      ChatMessage(
        at: DateTime.now(),
        direction: ChatDirection.outgoing,
        peer: host,
        text: line,
      ),
    );
    final Socks5Socket socket;
    try {
      socket = await node.connect(host, port, timeout: replyTimeout);
    } on Exception catch (e) {
      _system('cannot reach $host:$port: $e');
      rethrow;
    }
    try {
      socket.write('$line\n');
      await socket.flush();
      final reply = await utf8.decoder
          .bind(socket)
          .transform(const LineSplitter())
          .first
          .timeout(replyTimeout);
      _messages[index] = _messages[index].asDelivered();
      if (reply != line) {
        _add(
          ChatMessage(
            at: DateTime.now(),
            direction: ChatDirection.incoming,
            peer: host,
            text: reply,
          ),
        );
      }
      notifyListeners();
    } on TimeoutException {
      _system('no reply from $host within ${replyTimeout.inSeconds}s');
    } on StateError {
      _system('$host closed the connection without replying');
    } on Exception catch (e) {
      _system('$host: $e');
    } finally {
      socket.destroy();
    }
  }

  Future<void> _serve(TailscaleSocket socket) async {
    final address = socket.remoteAddress?.address;
    // Resolve the sender while the first bytes are already arriving; callbacks
    // chained on one future run in registration order, so lines stay ordered.
    final peerName = _resolvePeer(address);
    utf8.decoder
        .bind(socket)
        .transform(const LineSplitter())
        .listen(
          (line) {
            socket.write('$line\n'); // echo, like `tsnode echo`
            unawaited(
              peerName.then(
                (peer) => _add(
                  ChatMessage(
                    at: DateTime.now(),
                    direction: ChatDirection.incoming,
                    peer: peer,
                    text: line,
                  ),
                ),
              ),
            );
          },
          onError: (Object e) {
            unawaited(
              peerName.then((peer) => _system('$peer: read error: $e')),
            );
          },
          onDone: () => unawaited(socket.close()),
          cancelOnError: true,
        );
  }

  Future<String> _resolvePeer(String? address) async {
    final node = _node;
    if (address == null) return 'unknown peer';
    if (node == null) return address;
    try {
      final identity = await node.whoIs(address);
      return identity.node.shortName;
    } on TailscaleException {
      return address;
    }
  }

  int _add(ChatMessage message) {
    _messages.add(message);
    notifyListeners();
    return _messages.length - 1;
  }

  void _system(String text) => _add(
    ChatMessage(
      at: DateTime.now(),
      direction: ChatDirection.system,
      peer: '',
      text: text,
    ),
  );

  bool _disposed = false;

  @override
  void notifyListeners() {
    // detach() finishes asynchronously after dispose(); stay silent then.
    if (!_disposed) super.notifyListeners();
  }

  @override
  void dispose() {
    _disposed = true;
    unawaited(detach());
    super.dispose();
  }
}
